import type { Metadata } from "next";
import { Exo_2 } from "next/font/google";
import NavBar from "../components/NavBar";
import Footer from "../components/Footer";
import "./globals.css";
import { ThemeProvider } from "next-themes";

const inter = Exo_2({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <main className="h-full space-y-7">
          <NavBar />
          <section className="min-h-[80svh]">{children}</section>
          <Footer />
        </main>
      </body>
    </html>
  );
}
